languageCode = "en-us"
title        = "Inside the Box"
baseURL      = "http://www.jondelamotte.com/"
theme        = "hugo-privacy-cactus-theme"

[Params]

description = "The musings of Jon de la Motte"
