languageCode = "en-us"
title        = "~"
baseURL      = "http://www.jondelamotte.com/"
theme        = "clean"

[Params]

description = "The musings of Jon de la Motte"
name        = "Jon de la Motte"
